//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangThietBiDienTu.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public decimal DONGIA { get; set; }
        public int SOLUONG { get; set; }
        public string MOTA { get; set; }
        public string ANH { get; set; }
        public string MALOAISP { get; set; }
        public string MATH { get; set; }
        public string MATSKT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        public virtual THONGSOKYTHUAT THONGSOKYTHUAT { get; set; }
    }
}
